ProgDir: ./prog
FileType: mp4
DownloadedHistoryConfFile: config/downloaded.yaml
Programs:
  - Name: カルチャーラジオ 科学と人間
    Url: https://www.nhk.or.jp/radioondemand/json/3065/bangumi_3065_01.json
  - Name: カルチャーラジオ 文学の世界
    Url: https://www.nhk.or.jp/radioondemand/json/1929/bangumi_1929_01.json
