- ProgramID: "0058"
  ProgramTitle: FMシアター
  EpisodeID: "24191"
  EpisodeTitle: 「風よとどけよ」
- ProgramID: "0058"
  ProgramTitle: FMシアター
  EpisodeID: "23894"
  EpisodeTitle: 「ボクの、いじわるでえらそうなヒール」
- ProgramID: "0058"
  ProgramTitle: FMシアター
  EpisodeID: "23669"
  EpisodeTitle: 「夜明けの舞」
- ProgramID: "0058"
  ProgramTitle: FMシアター
  EpisodeID: "23420"
  EpisodeTitle: 「エンディング・カット」
- ProgramID: "0058"
  ProgramTitle: FMシアター
  EpisodeID: "23200"
  EpisodeTitle: 「上越新幹線にて」
- ProgramID: "0058"
  ProgramTitle: FMシアター
  EpisodeID: "23001"
  EpisodeTitle: 「幻タクシー」
